spring:
  application:
    name: JAVATEST
  datasource:
    url: jdbc:mysql://localhost:3306/UserDb
    username: root
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082



