spring:
  application:
    name: JAVATEST
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082



